#!/usr/bin/with-contenv bash
# shellcheck shell=bash

cd /app/lidarr/bin || exit 1

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
    exec s6-setuidgid abc \
        /app/lidarr/bin/Lidarr \
        -nobrowser \
        -data=/config
else
    exec /app/lidarr/bin/Lidarr \
        -nobrowser \
        -data=/config
fi