name: Bug report
description: Create a report to help improve the container
title: "[BUG] "
labels:
  - bug

body:
  - type: checkboxes
    attributes:
      label: Existing issue check
      description: Search existing issues before creating a new one.
      options:
        - label: I searched existing issues
          required: true

  - type: input
    attributes:
      label: Container version
      placeholder: lscr.io/linuxserver/lidarr:latest
    validations:
      required: true

  - type: textarea
    attributes:
      label: Current behavior
      description: What is happening?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Expected behavior
      description: What should happen?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Deploy container
        2. Open web UI
        3. Trigger action
        4. Observe error
    validations:
      required: true

  - type: textarea
    attributes:
      label: Environment
      value: |
        - OS:
        - Docker version:
        - Docker compose version:
    validations:
      required: true

  - type: dropdown
    attributes:
      label: CPU architecture
      options:
        - x86_64
        - arm64
    validations:
      required: true

  - type: textarea
    attributes:
      label: Docker compose
      render: yaml
    validations:
      required: true

  - type: textarea
    attributes:
      label: Container logs
      render: bash
    validations:
      required: true