name: Feature request
description: Suggest a new feature or improvement
title: "[FEAT] "
labels:
  - enhancement

body:
  - type: checkboxes
    attributes:
      label: Existing feature request check
      options:
        - label: I searched existing feature requests
          required: true

  - type: textarea
    attributes:
      label: Requested change
    validations:
      required: true

  - type: textarea
    attributes:
      label: Why is this useful?
    validations:
      required: true

  - type: textarea
    attributes:
      label: Proposed implementation