name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/first-interaction@v1
      with:
        issue-message: 'This image is deprecated. We will not offer support for this image and it will not be updated. The [README](https://github.com/linuxserver/docker-lidarr/blob/nightly-alpine/README.md) may have additional information. Thanks for opening your first issue here! Be sure to follow the [bug](https://github.com/linuxserver/docker-lidarr/blob/nightly-alpine/.github/ISSUE_TEMPLATE/issue.bug.md) or [feature](https://github.com/linuxserver/docker-lidarr/blob/nightly-alpine/.github/ISSUE_TEMPLATE/issue.feature.md) issue templates!'
        pr-message: 'This image is deprecated. We will not offer support for this image and it will not be updated. The [README](https://github.com/linuxserver/docker-lidarr/blob/nightly-alpine/README.md) may have additional information. Thanks for opening this pull request! Be sure to follow the [pull request template](https://github.com/linuxserver/docker-lidarr/blob/nightly-alpine/.github/PULL_REQUEST_TEMPLATE.md)!'
        repo-token: ${{ secrets.GITHUB_TOKEN }}
